# Site settings
lang: en-US
permalink: '/:path'

exclude:
  - README.md
  - vendor
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - BACKUPS

markdown: kramdown
kramdown:
  html_to_native:
    elements:
      - hr
      - img

destination: build
source: source
