# Site settings
lang: en-US
permalink: "/:path"
destination: build
source: source

# This must not have a trailing slash
url: "https://example.com"

# Documentation at https://jekyllrb.com/docs/configuration/liquid/
liquid:
  error_mode: strict
  strict_variables: false # Unusable as per https://github.com/Shopify/liquid/issues/1404
  strict_filters: true
